name: original-covetplugins
version: 1.0-SNAPSHOT
main: me.covetplugins.Main
api-version: 1.18
author: jefry
description: Your plugin description

commands:
  scoreboard:
    description: Control the scoreboard functionality
    usage: /scoreboard <on|off|reload>
    aliases: [sb]
    permission: covet.scoreboard

permissions:
  covet.scoreboard:
    description: Permission to use the /scoreboard command
    default: op
